# https://riscof.readthedocs.io/en/latest/inputs.html#config-syntax

[RISCOF]
ReferencePlugin=sail_cSim
ReferencePluginPath=riscof-plugins/rv64/sail_cSim
DUTPlugin=spike_simple
DUTPluginPath=riscof-plugins/rv64/spike_simple

[spike_simple]
pluginpath=riscof-plugins/rv64/spike_simple
ispec=rv64i_spike_simple_isa.yaml
pspec=riscof-plugins/rv64/spike_simple/spike_simple_platform.yaml
target_run=1
jobs=8

[sail_cSim]
pluginpath=riscof-plugins/rv64/sail_cSim
ispec=rv64i_sail_isa.yaml
pspec=riscof-plugins/rv64/sail_cSim/sail_platform.yaml
jobs=8
